[project]
name = "gpt2-fine-tune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.0",
    "numpy>=2.3.2",
    "torch>=2.7.1",
    "transformers>=4.54.1",
]
